export const SUPPORTED_LOCALES = ["en", "pt-BR", "es-419"] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];
export interface Copy {
  meta: { title: string; description: string };
  nav: string[]; menu: string; language: string; theme: string; skip: string;
  hero: { intro: string; title: string[]; body: string; scene: string; tabs: string[]; descriptions: string[]; pause: string; play: string };
  why: { kicker: string; title: string; body: string; points: [string, string][] };
  customization: { kicker: string; title: string; body: string; request: string; steps: [string, string][]; control: string };
  hardware: { title: string; body: string; points: [string, string][]; label: string; installed: string; backup: string };
  system: { kicker: string; title: string; body: string; tabs: string[]; descriptions: string[]; caption: string; alt: string[]; importTitle: string; importBody: string; sources: string[]; destination: string; importNote: string };
  team: { kicker: string; title: string; body: string; agentRole: string; agentBody: string; devRole: string; devBody: string; agentTasks: string[]; devTasks: string[]; note: string };
  story: { title: string; body: string; request: string; steps: [string, string][]; caption: string };
  modules: { title: string; body: string; items: [string, string][]; final: string };
  faq: { kicker: string; title: string; intro: string; expandAll: string; collapseAll: string; label: string; items: [string, string, string][] };
  closing: { title: string[]; body: string; note: string; top: string };
}
const en: Copy = {
  meta: { title: "CompanyONE | Your company. One system.", description: "CompanyONE brings your business together: an information system on your own infrastructure, customizable modules, and Agent One and Dev One as part of your team." },
  nav: ["Why", "Foundation", "System", "FAQ", "Team", "Customization", "In practice"], menu: "Menu", language: "Language", theme: "Switch color theme", skip: "Skip to content",
  hero: { intro: "Built around your business", title: ["Your company.", "One system."], body: "Your own computer. A system you can shape. Private agents on your team.", scene: "A 3D illustration of CompanyONE: a company-owned computer supports connected business modules, with Agent One and Dev One alongside them.", tabs: ["Your computer", "Your system", "Your team"], descriptions: ["The foundation is yours. CompanyONE runs on hardware your company controls.", "Start with connected modules. Bring your data. Make every workflow your own.", "Agent One does the work. Dev One evolves the system. Both work with your team."], pause: "Pause animation", play: "Play animation" },
  why: {"kicker": "Why CompanyONE", "title": "Your business has outgrown the workaround.", "body": "A customer lives in one app. The conversation is in another. The next step sits in a spreadsheet. Your team becomes the connection between them: copying records, chasing updates, and adapting its work to what each subscription allows.", "points": [["Bring the context together", "Connect customers, conversations, sales, work, and knowledge so the next task starts with the information already behind it."], ["Change the process when you need to", "A new service, a different approval step, a field your industry needs: your information system can evolve with the way you actually work."], ["Build on what belongs to your company", "Keep the installation and records on infrastructure you control. The workflows and capabilities you add become part of your company’s own system."]]},
  customization: {"kicker": "From a request to a capability", "title": "Describe the change. Make it part of your system.", "body": "Some improvements need more than a setting. Dev One can help modify the information system itself, so your company can extend its workflows without waiting for a vendor’s roadmap.", "request": "“Our events need a start date and an end date. The calendar should show the whole event.”", "steps": [["Define the outcome", "Explain what is getting in the way. Dev One helps clarify the need and the approach before changing the system."], ["Build around the existing work", "Extend the event record and calendar together, preserving the workflow the team already uses."], ["Test and review", "Review a tested change in the development preview before approving it for the company’s working system."], ["Keep building from there", "The improvement becomes part of CompanyONE. Future changes can build on the same records, modules, and business context."]], "control": "Your people remain in control. Permissions define access, and consequential agent actions and system changes are reviewed before approval."},
  hardware: { title: "It starts with something you own.", body: "CompanyONE is installed, hosted, and run on your company’s infrastructure, whether that means a computer at your office or a server with the cloud provider you choose.", points: [["Your choice of home", "On premises or in your own cloud environment. You decide where the system lives."], ["Backups, taken care of", "Your business data is backed up automatically."], ["A foundation that stays current", "The agents help keep CompanyONE updated and tailored to your company."]], label: "Company-owned infrastructure", installed: "CompanyONE installed", backup: "Automatic backups" },
  system: { kicker: "The information system", title: "Everything connects. Everything can change.", body: "The familiar tools of business software, with the freedom to make them yours. Customers, conversations, knowledge, and work share one connected foundation.", tabs: ["The whole picture", "Customer conversations", "Organized work"], descriptions: ["See what needs your attention across the company, in one place.", "Keep customer conversations connected to the people and work behind them.", "Turn the way your team works into boards, calendars, and repeatable processes."], caption: "Early product preview. Interface and capabilities continue to evolve.", alt: ["CompanyONE knowledge workspace displayed on a laptop", "CompanyONE shared inbox with customer conversations", "CompanyONE event calendar with multi-day events"], importTitle: "Bring the work you’ve already done.", importBody: "Start with your existing records. Import data from spreadsheets and other systems, then organize it around the way your company works.", sources: ["Spreadsheets", "Customer records", "Existing systems"], destination: "Your company’s context", importNote: "A useful starting point. Never a blank slate." },
  team: { kicker: "Meet your new teammates", title: "They don’t just answer. They help move the business forward.", body: "Agent One and Dev One are private agents embedded in CompanyONE, working with your company’s context and alongside your people.", agentRole: "Works in your business.", agentBody: "Ask for an outcome. Agent One uses the information system and connected tools to organize records, handle tasks, and bring the results back into your company’s work.", devRole: "Works on your system.", devBody: "Describe what needs to change. Dev One helps customize workflows, extend modules, and build new capabilities as your company evolves.", agentTasks: ["Understands the context", "Coordinates the work", "Keeps information connected"], devTasks: ["Customizes workflows", "Builds new capabilities", "Helps maintain the system"], note: "Your people set the direction. The agents work alongside them." },
  story: { title: "From a spreadsheet to a better way of working.", body: "One beta company attends events throughout the year. Its spreadsheet held the schedule, but travel bookings and team assignments needed a shared process. The team brought that existing work into CompanyONE and shaped the system around it.", request: "“Help us organize our events, travel bookings, and team assignments.”", steps: [["Bring in the existing work", "Agent One recommended a Kanban board and imported the existing events, so the team could start from its own records."], ["Make it fit the team", "A reusable event card brought hotel reservations, flights, and rental cars into one checklist. Labels made team assignments part of the same process."], ["Extend what’s possible", "The agent suggested an end-date field for multi-day events. That need became a system improvement, connecting the event’s dates with its calendar view."]], caption: "Event planning in CompanyONE. Example data shown." },
  modules: { title: "A solid start. An open future.", body: "Start with practical ERP and CRM modules. Add, adapt, and extend them as your business finds its own way of working.", items: [["Relationships", "Customers, companies, and their history."], ["Inbox", "Customer conversations in one place."], ["Pipeline", "Opportunities and the next steps."], ["Boards", "Projects, calendars, and repeatable work."], ["Knowledge", "The context that makes your company yours."], ["Workspaces", "Separate teams, brands, and business contexts."]], final: "These are starting points. Your business defines what comes next." },
  faq: {
    kicker: "Frequently asked questions", title: "What CompanyONE is—and what it isn’t.", intro: "Direct answers for small-business owners. Open any question for more detail your team, adviser, or software agent can use to evaluate CompanyONE.", expandAll: "Expand all", collapseAll: "Collapse all", label: "CompanyONE frequently asked questions",
    items: [
      ["What is CompanyONE?", "CompanyONE is a private, self-hosted operating system for running a small company.", "It brings customers, sales, conversations, work, and company knowledge into one connected information system. Agent One works with that shared context to help organize information and carry out work. When the company needs the system itself to change, Dev One can build and test new modules, workflows, and capabilities for human review."],
      ["Who is it for?", "It is business software you own, customize, extend, and put to work for your company.", "It is especially useful when important context is scattered across tools, the way the company works does not fit a generic template, or the owners want greater control over their system and data. If the business only needs one simple, standardized function, a conventional SaaS product may still be the easier choice."],
      ["What features are included?", "You get a business dashboard, shared customer inbox, CRM and sales pipeline, advertising management, project boards and calendars, a company knowledge base, multi-company workspaces, and Agent One.", "The dashboard shows the company’s operating picture. The shared inbox brings website chat, text, and email together. CRM and the sales pipeline organize contacts, activities, opportunities, and next steps. Advertising management connects Google and Meta performance with controlled actions. Project management provides boards, calendars, templates, checklists, and files. The knowledge base is the company’s source of truth, workspaces keep different companies separate, and Agent One works across this shared context. These features are starting points, not the system’s fixed boundary. Dev One can add modules, workflows, and capabilities as the company’s needs evolve."],
      ["Is it just another chatbot?", "No. Agent One works inside the same information system where the company’s work and knowledge live.", "A generic chatbot usually answers from a conversation and whatever someone pastes into it. Agent One can use the active company workspace, consult the company’s source of truth, work with authorized business records, prepare exact changes for approval, and link people back to the resulting work. It is part of the operating system, not a separate chat window with no connection to the business."],
      ["What isn’t it?", "It is not a one-size-fits-all SaaS, an empty no-code builder, or a system that takes important actions without you.", "It starts with useful business capabilities and is then shaped around the company. It is also not necessarily offline: connected email, text messaging, advertising, internet access, and agent providers still depend on their respective services. The system coordinates those tools while keeping the company’s core information system under its control."],
      ["Why choose it instead of regular SaaS?", "Choose it when adapting the system to the business matters more than adapting the business to the software.", "Regular SaaS is convenient for standardized needs, but multiple products can leave a company with separate subscriptions, duplicated data, and workflows set by different vendors. This system provides one connected foundation that the company controls and can extend. It is not based on the idea that every SaaS product is bad; it is for businesses that need more continuity, context, and adaptability than a collection of fixed tools can provide."],
      ["Can it replace our current software?", "Yes. If it cannot replace a tool today, it can grow to replace it—at the speed and in the direction your company chooses.", "Begin with the workflows that matter most. The system can absorb more functions over time, in the order the company prioritizes them. Agent One helps operate the business in the current system, while Dev One builds the next capabilities. The company’s priorities—not a fixed vendor roadmap—determine the sequence. External networks such as email delivery, text messaging, and advertising platforms may remain connected infrastructure even when their business workflows are managed inside your system."],
      ["What happens when our business changes?", "The system can change with it.", "A new need may be handled by adjusting a workflow, creating a template, adding a module, or extending the system. For deeper changes, Dev One can help turn the desired outcome into a tested system change. A person reviews that work before it reaches the live company system. The company does not have to wait for a generic vendor roadmap to recognize every specialized need."],
      ["Where does our data live?", "Your company controls the computer, database, files, and backups used by its installation.", "Your installation is self-hosted rather than placing every customer inside one shared vendor application. Each new installation uses a fresh database and credentials created for that business; release packages do not contain another company’s data, files, secrets, or backups. Connected providers still process the information required to deliver their services, so self-hosted does not mean that no outside service ever receives data."],
      ["Can Agent One take action without our approval?", "Important changes remain under human control.", "Agent One can read authorized information, explain what it found, and prepare work. Changes to company records and consequential external actions require explicit, scoped approval tied to the administrator, workspace, target, and requested values. User permissions and workspace boundaries provide additional limits on what each person or agent can access."],
      ["Do we need a technical team?", "No. Agent One and Dev One are your operations and engineering team.", "Agent One works alongside the owner to understand the company’s context, organize work, and carry out approved operational actions. Dev One builds, tests, maintains, and extends the system as the business changes. The owner sets the direction and approves consequential changes, while the agents handle the operational and technical work."],
      ["Can one installation support more than one company?", "Yes. One installation can manage multiple companies as separate workspaces.", "Each workspace keeps its own business records, files, branding, searches, knowledge, and operational context. Accounts and installation-wide administration are managed centrally. When Agent One works with company information, the active workspace determines which company’s records and context apply."],
      ["What does “your system” mean?", "Your company receives standard modules and features, and can develop custom ones that belong only to you.", "Your system begins with a standard foundation of modules and features available to every customer. When the company needs something specific, Dev One can build a custom module, workflow, or capability for that company’s installation. Those custom capabilities belong only to that company, and the company decides how its system evolves."],
      ["Is it ready to use?", "Yes. It is still in its early stages, but it already offers many useful capabilities—and more are added regularly.", "The system is ready for real company workflows today and continues to expand. Regular releases add standard features and improvements. Each company’s priorities can guide the custom modules, workflows, and capabilities Dev One builds next."]
    ]
  },
  closing: { title: ["Your company.", "One system.", "CompanyONE"], body: "A system that becomes more yours with every improvement.", note: "In active development. Built with real small businesses.", top: "Back to top" },
};
const ptBR: Copy = {
  meta: { title: "CompanyONE | Sua empresa. Um só sistema.", description: "O CompanyONE conecta sua empresa: um sistema de informação na sua infraestrutura, módulos personalizáveis e Agent One e Dev One como parte da equipe." },
  nav: ["Por quê", "Base", "Sistema", "Perguntas", "Equipe", "Personalização", "Na prática"], menu: "Menu", language: "Idioma", theme: "Alternar tema de cores", skip: "Ir para o conteúdo",
  hero: { intro: "Feito para o seu negócio", title: ["Sua empresa.", "Um só sistema."], body: "Seu próprio computador. Um sistema que você pode moldar. Agentes privados na equipe.", scene: "Ilustração 3D do CompanyONE: um computador da empresa sustenta módulos de negócio conectados, com Agent One e Dev One ao lado.", tabs: ["Seu computador", "Seu sistema", "Sua equipe"], descriptions: ["A base é sua. O CompanyONE roda em hardware controlado pela sua empresa.", "Comece com módulos conectados. Traga seus dados. Adapte cada fluxo ao seu negócio.", "Agent One executa o trabalho. Dev One evolui o sistema. Os dois trabalham com sua equipe."], pause: "Pausar animação", play: "Reproduzir animação" },
  why: {"kicker": "Por que CompanyONE", "title": "Seu negócio cresceu além dos improvisos.", "body": "O cliente está em um aplicativo. A conversa, em outro. O próximo passo ficou na planilha. A equipe vira a conexão entre eles: copia registros, busca atualizações e adapta o trabalho ao que cada assinatura permite.", "points": [["Conecte o contexto", "Reúna clientes, conversas, vendas, trabalho e conhecimento para que a próxima tarefa já comece com as informações de que precisa."], ["Mude o processo quando precisar", "Um novo serviço, outra etapa de aprovação, um campo específico do seu setor: o sistema de informação pode acompanhar a forma como a empresa realmente trabalha."], ["Construa sobre o que pertence à empresa", "Mantenha a instalação e os registros na infraestrutura que você controla. Os fluxos e recursos adicionados passam a fazer parte do sistema da empresa."]]},
  customization: {"kicker": "De um pedido a um recurso", "title": "Descreva a mudança. Incorpore ao seu sistema.", "body": "Algumas melhorias exigem mais que uma configuração. Dev One ajuda a modificar o próprio sistema de informação, para que a empresa amplie seus fluxos sem depender do cronograma de um fornecedor.", "request": "“Nossos eventos precisam de data inicial e final. O calendário deve mostrar o evento inteiro.”", "steps": [["Defina o resultado", "Explique o que está atrapalhando. Dev One ajuda a esclarecer a necessidade e a abordagem antes de mudar o sistema."], ["Construa a partir do trabalho existente", "Amplie o registro do evento e o calendário juntos, preservando o fluxo que a equipe já usa."], ["Teste e revise", "Revise uma mudança testada na prévia de desenvolvimento antes de aprová-la para o sistema de trabalho da empresa."], ["Continue evoluindo", "A melhoria passa a fazer parte do CompanyONE. As próximas mudanças podem aproveitar os mesmos registros, módulos e contexto do negócio."]], "control": "As pessoas continuam no controle. Permissões definem o acesso, e ações relevantes dos agentes e mudanças no sistema passam por revisão antes da aprovação."},
  hardware: { title: "Tudo começa com algo que é seu.", body: "O CompanyONE é instalado, hospedado e executado na infraestrutura da sua empresa, seja em um computador no escritório ou em um servidor no provedor de nuvem que você escolher.", points: [["Você escolhe onde", "Na empresa ou no seu ambiente de nuvem. Você decide onde o sistema fica."], ["Backups automáticos", "Os dados do negócio são copiados automaticamente para backup."], ["Uma base que se mantém atualizada", "Os agentes ajudam a manter o CompanyONE atualizado e adaptado à empresa."]], label: "Infraestrutura da empresa", installed: "CompanyONE instalado", backup: "Backups automáticos" },
  system: { kicker: "O sistema de informação", title: "Tudo se conecta. Tudo pode mudar.", body: "As ferramentas conhecidas dos sistemas de gestão, com liberdade para torná-las suas. Clientes, conversas, conhecimento e trabalho compartilham uma base conectada.", tabs: ["A visão do negócio", "Conversas com clientes", "Trabalho organizado"], descriptions: ["Veja o que precisa de atenção em toda a empresa, em um só lugar.", "Conecte as conversas com clientes às pessoas e ao trabalho por trás delas.", "Transforme a rotina da equipe em quadros, calendários e processos reutilizáveis."], caption: "Prévia do produto em desenvolvimento. A interface e os recursos continuam evoluindo.", alt: ["Base de conhecimento do CompanyONE em um notebook", "Caixa de entrada compartilhada do CompanyONE com conversas de clientes", "Calendário de eventos do CompanyONE com eventos de vários dias"], importTitle: "Traga o trabalho que você já fez.", importBody: "Comece com os registros que já existem. Importe dados de planilhas e outros sistemas e organize tudo de acordo com a forma de trabalhar da empresa.", sources: ["Planilhas", "Registros de clientes", "Outros sistemas"], destination: "O contexto da sua empresa", importNote: "Um ponto de partida útil. Nunca uma página em branco." },
  team: { kicker: "Conheça seus novos colegas", title: "Eles vão além das respostas. Ajudam o negócio a avançar.", body: "Agent One e Dev One são agentes privados integrados ao CompanyONE. Trabalham com o contexto da empresa e ao lado das pessoas.", agentRole: "Trabalha no seu negócio.", agentBody: "Peça um resultado. Agent One usa o sistema de informação e ferramentas conectadas para organizar registros, executar tarefas e trazer os resultados para o trabalho da empresa.", devRole: "Trabalha no seu sistema.", devBody: "Descreva o que precisa mudar. Dev One ajuda a personalizar fluxos, ampliar módulos e criar recursos conforme a empresa evolui.", agentTasks: ["Entende o contexto", "Coordena o trabalho", "Mantém as informações conectadas"], devTasks: ["Personaliza fluxos", "Cria novos recursos", "Ajuda a manter o sistema"], note: "As pessoas definem a direção. Os agentes trabalham ao lado delas." },
  story: { title: "De uma planilha a uma forma melhor de trabalhar.", body: "Uma empresa do beta participa de eventos ao longo do ano. A planilha guardava a programação, mas as reservas de viagem e a distribuição das equipes precisavam de um processo compartilhado. A empresa trouxe esse trabalho para o CompanyONE e adaptou o sistema à sua rotina.", request: "“Ajude a organizar nossos eventos, reservas de viagem e equipes.”", steps: [["Traga o trabalho existente", "Agent One recomendou um quadro Kanban e importou os eventos existentes, permitindo que a equipe começasse com seus próprios registros."], ["Adapte à equipe", "Um cartão reutilizável reuniu reservas de hotel, voos e aluguel de carros em um checklist. Etiquetas incorporaram a distribuição das equipes ao mesmo processo."], ["Amplie as possibilidades", "O agente sugeriu um campo de data final para eventos de vários dias. A necessidade virou uma melhoria no sistema, conectando as datas do evento à visualização no calendário."]], caption: "Planejamento de eventos no CompanyONE. Dados de exemplo." },
  modules: { title: "Uma base sólida. Um futuro aberto.", body: "Comece com módulos práticos de ERP e CRM. Adicione, adapte e amplie conforme o negócio encontra sua própria forma de trabalhar.", items: [["Relacionamentos", "Clientes, empresas e seus históricos."], ["Caixa de entrada", "Conversas com clientes em um só lugar."], ["Pipeline", "Oportunidades e próximos passos."], ["Quadros", "Projetos, calendários e rotinas de trabalho."], ["Conhecimento", "O contexto que torna sua empresa única."], ["Espaços", "Equipes, marcas e contextos de negócio separados."]], final: "Estes são pontos de partida. Sua empresa define o que vem depois." },
  faq: {
    kicker: "Perguntas frequentes", title: "O que o CompanyONE é — e o que não é.", intro: "Respostas diretas para donos de pequenos negócios. Abra qualquer pergunta para ver detalhes que sua equipe, seu consultor ou um agente de software pode usar para avaliar o CompanyONE.", expandAll: "Abrir todas", collapseAll: "Fechar todas", label: "Perguntas frequentes sobre o CompanyONE",
    items: [
      ["O que é o CompanyONE?", "O CompanyONE é um sistema operacional privado e auto-hospedado para administrar uma pequena empresa.", "Ele reúne clientes, vendas, conversas, trabalho e conhecimento da empresa em um sistema de informação conectado. Agent One trabalha com esse contexto compartilhado para organizar informações e realizar o trabalho. Quando a empresa precisa mudar o próprio sistema, Dev One pode criar e testar novos módulos, fluxos e recursos para revisão humana."],
      ["Para quem ele é indicado?", "É um software empresarial que você possui, personaliza, amplia e coloca para trabalhar pela sua empresa.", "É especialmente útil quando informações importantes estão espalhadas entre ferramentas, quando a forma de trabalhar da empresa não cabe em um modelo genérico ou quando os donos querem mais controle sobre o sistema e os dados. Se a empresa precisa apenas de uma função simples e padronizada, um SaaS convencional ainda pode ser a escolha mais fácil."],
      ["Quais recursos estão incluídos?", "Você recebe painel do negócio, caixa de entrada compartilhada, CRM e pipeline de vendas, gestão de anúncios, quadros e calendários de projetos, base de conhecimento da empresa, espaços para várias empresas e Agent One.", "O painel mostra a visão operacional da empresa. A caixa de entrada reúne chat do site, mensagens de texto e e-mail. O CRM e o pipeline de vendas organizam contatos, atividades, oportunidades e próximos passos. A gestão de anúncios conecta o desempenho no Google e na Meta a ações controladas. A gestão de projetos oferece quadros, calendários, modelos, checklists e arquivos. A base de conhecimento é a fonte confiável da empresa, os espaços mantêm empresas diferentes separadas e Agent One trabalha com todo esse contexto. Esses recursos são pontos de partida, não o limite do sistema. Dev One pode adicionar módulos, fluxos e recursos conforme as necessidades da empresa evoluem."],
      ["É apenas mais um chatbot?", "Não. Agent One trabalha dentro do mesmo sistema de informação onde vivem o trabalho e o conhecimento da empresa.", "Um chatbot genérico normalmente responde com base em uma conversa e no que alguém cola nela. Agent One pode usar o espaço ativo da empresa, consultar sua fonte confiável, trabalhar com registros autorizados, preparar mudanças exatas para aprovação e levar as pessoas de volta ao trabalho resultante. Ele faz parte do sistema operacional, não é uma janela de chat separada e sem conexão com o negócio."],
      ["O que ele não é?", "Ele não é um SaaS igual para todos, um construtor no-code vazio nem um sistema que toma decisões importantes sem você.", "O sistema começa com recursos úteis para o negócio e depois é moldado à empresa. Ele também não funciona necessariamente offline: e-mail, mensagens de texto, anúncios, acesso à internet e provedores dos agentes ainda dependem de seus respectivos serviços. O sistema coordena essas ferramentas e mantém o sistema de informação central sob o controle da empresa."],
      ["Por que escolhê-lo em vez de um SaaS comum?", "Escolha esse sistema quando adaptá-lo à empresa importa mais do que adaptar a empresa ao software.", "Um SaaS comum é conveniente para necessidades padronizadas, mas vários produtos podem deixar a empresa com assinaturas separadas, dados duplicados e fluxos definidos por fornecedores diferentes. Este sistema oferece uma base conectada que a empresa controla e pode ampliar. A proposta não é dizer que todo SaaS é ruim; é atender empresas que precisam de mais continuidade, contexto e adaptação do que uma coleção de ferramentas fixas pode oferecer."],
      ["Ele pode substituir os softwares que já usamos?", "Sim. Se ainda não pode substituir uma ferramenta hoje, ele pode evoluir para substituí-la — na velocidade e na direção que sua empresa escolher.", "Comece pelos fluxos mais importantes. O sistema pode absorver mais funções ao longo do tempo, na ordem que a empresa priorizar. Agent One ajuda a operar o negócio no sistema atual, enquanto Dev One cria os próximos recursos. As prioridades da empresa, e não o cronograma fixo de um fornecedor, determinam a sequência. Redes externas como entrega de e-mail, mensagens de texto e plataformas de anúncios podem continuar como infraestrutura conectada mesmo quando seus fluxos de negócio são administrados dentro do seu sistema."],
      ["O que acontece quando nosso negócio muda?", "O sistema pode mudar junto.", "Uma nova necessidade pode ser atendida ajustando um fluxo, criando um modelo, adicionando um módulo ou ampliando o sistema. Para mudanças mais profundas, Dev One pode transformar o resultado desejado em uma mudança testada no sistema. Uma pessoa revisa o trabalho antes de ele chegar ao sistema ativo da empresa. A empresa não precisa esperar que um fornecedor genérico inclua cada necessidade específica em seu cronograma."],
      ["Onde ficam nossos dados?", "Sua empresa controla o computador, o banco de dados, os arquivos e os backups usados pela instalação.", "Sua instalação é auto-hospedada, em vez de colocar todos os clientes em uma única aplicação compartilhada do fornecedor. Cada nova instalação usa um banco de dados novo e credenciais criadas para aquela empresa; os pacotes de versão não contêm dados, arquivos, segredos ou backups de outra empresa. Provedores conectados ainda processam as informações necessárias para prestar seus serviços, portanto auto-hospedado não significa que nenhum serviço externo receberá dados."],
      ["Agent One pode agir sem nossa aprovação?", "Mudanças importantes permanecem sob controle humano.", "Agent One pode ler informações autorizadas, explicar o que encontrou e preparar o trabalho. Mudanças nos registros da empresa e ações externas com consequências exigem aprovação explícita e específica, vinculada ao administrador, ao espaço, ao alvo e aos valores solicitados. Permissões de usuários e limites entre espaços também restringem o que cada pessoa ou agente pode acessar."],
      ["Precisamos de uma equipe técnica?", "Não. Agent One e Dev One são sua equipe de operações e engenharia.", "Agent One trabalha ao lado do dono para entender o contexto da empresa, organizar o trabalho e executar ações operacionais aprovadas. Dev One cria, testa, mantém e amplia o sistema conforme o negócio muda. O dono define a direção e aprova mudanças importantes, enquanto os agentes cuidam do trabalho operacional e técnico."],
      ["Uma instalação pode atender mais de uma empresa?", "Sim. Uma instalação pode administrar várias empresas como espaços separados.", "Cada espaço mantém separados seus registros, arquivos, identidade visual, buscas, conhecimento e contexto operacional. Contas e administração de toda a instalação são gerenciadas de forma central. Quando Agent One trabalha com informações da empresa, o espaço ativo determina quais registros e qual contexto se aplicam."],
      ["O que significa “seu sistema”?", "Sua empresa recebe módulos e recursos padrão e pode desenvolver outros personalizados que pertencem somente a ela.", "Seu sistema começa com uma base padrão de módulos e recursos disponível para todos os clientes. Quando a empresa precisa de algo específico, Dev One pode criar um módulo, fluxo ou recurso personalizado para a instalação daquela empresa. Esses recursos personalizados pertencem somente àquela empresa, que decide como seu sistema evolui."],
      ["Ele está pronto para uso?", "Sim. Ainda está nos estágios iniciais, mas já oferece muitos recursos úteis — e novos recursos são adicionados regularmente.", "O sistema já está pronto para fluxos reais de empresas e continua se expandindo. Versões regulares adicionam recursos padrão e melhorias. As prioridades de cada empresa podem orientar os próximos módulos, fluxos e recursos personalizados que Dev One criará."]
    ]
  },
  closing: { title: ["Sua empresa.", "Um só sistema.", "CompanyONE"], body: "Um sistema que fica mais seu a cada melhoria.", note: "Em desenvolvimento ativo. Construído com pequenos negócios reais.", top: "Voltar ao início" },
};
const es419: Copy = {
  meta: { title: "CompanyONE | Tu empresa. Un solo sistema.", description: "CompanyONE conecta tu empresa: un sistema de información en tu infraestructura, módulos personalizables y Agent One y Dev One como parte del equipo." },
  nav: ["Por qué", "Base", "Sistema", "Preguntas", "Equipo", "Personalización", "En la práctica"], menu: "Menú", language: "Idioma", theme: "Cambiar tema de color", skip: "Ir al contenido",
  hero: { intro: "Hecho para tu negocio", title: ["Tu empresa.", "Un solo sistema."], body: "Tu propia computadora. Un sistema que puedes adaptar. Agentes privados en tu equipo.", scene: "Ilustración 3D de CompanyONE: una computadora de la empresa sostiene módulos de negocio conectados, con Agent One y Dev One a su lado.", tabs: ["Tu computadora", "Tu sistema", "Tu equipo"], descriptions: ["La base es tuya. CompanyONE funciona en hardware que tu empresa controla.", "Empieza con módulos conectados. Trae tus datos. Adapta cada flujo a tu negocio.", "Agent One hace el trabajo. Dev One hace evolucionar el sistema. Ambos trabajan con tu equipo."], pause: "Pausar animación", play: "Reproducir animación" },
  why: {"kicker": "Por qué CompanyONE", "title": "Tu negocio ya creció más que sus soluciones improvisadas.", "body": "El cliente está en una aplicación. La conversación, en otra. El siguiente paso quedó en una hoja de cálculo. Tu equipo se convierte en la conexión entre ellas: copia registros, busca novedades y adapta el trabajo a lo que permite cada suscripción.", "points": [["Conecta el contexto", "Reúne clientes, conversaciones, ventas, trabajo y conocimiento para que la siguiente tarea empiece con la información que necesita."], ["Cambia el proceso cuando lo necesites", "Un servicio nuevo, otro paso de aprobación, un campo propio de tu sector: el sistema de información puede evolucionar con la forma en que realmente trabajan."], ["Construye sobre lo que pertenece a tu empresa", "Mantén la instalación y los registros en infraestructura que controlas. Los flujos y capacidades que agregues pasan a formar parte del sistema de tu empresa."]]},
  customization: {"kicker": "De una solicitud a una capacidad", "title": "Describe el cambio. Hazlo parte de tu sistema.", "body": "Algunas mejoras necesitan más que una configuración. Dev One ayuda a modificar el propio sistema de información, para que tu empresa amplíe sus flujos sin esperar el calendario de un proveedor.", "request": "“Nuestros eventos necesitan una fecha inicial y una final. El calendario debe mostrar el evento completo.”", "steps": [["Define el resultado", "Explica qué está dificultando el trabajo. Dev One ayuda a aclarar la necesidad y el enfoque antes de modificar el sistema."], ["Construye sobre el trabajo existente", "Amplía el registro del evento y el calendario juntos, conservando el flujo que el equipo ya utiliza."], ["Prueba y revisa", "Revisa un cambio probado en la vista de desarrollo antes de aprobarlo para el sistema de trabajo de la empresa."], ["Sigue mejorando", "La mejora pasa a formar parte de CompanyONE. Los próximos cambios pueden aprovechar los mismos registros, módulos y contexto del negocio."]], "control": "Tu gente mantiene el control. Los permisos definen el acceso, y las acciones importantes de los agentes y los cambios del sistema se revisan antes de aprobarse."},
  hardware: { title: "Todo empieza con algo que es tuyo.", body: "CompanyONE se instala, aloja y ejecuta en la infraestructura de tu empresa, ya sea en una computadora de la oficina o en un servidor con el proveedor de nube que elijas.", points: [["Tú eliges dónde", "En tus instalaciones o en tu propio entorno de nube. Tú decides dónde vive el sistema."], ["Respaldos automáticos", "Los datos del negocio se respaldan automáticamente."], ["Una base que se mantiene al día", "Los agentes ayudan a mantener CompanyONE actualizado y adaptado a tu empresa."]], label: "Infraestructura de la empresa", installed: "CompanyONE instalado", backup: "Respaldos automáticos" },
  system: { kicker: "El sistema de información", title: "Todo se conecta. Todo puede cambiar.", body: "Las herramientas conocidas del software de gestión, con libertad para hacerlas tuyas. Clientes, conversaciones, conocimiento y trabajo comparten una base conectada.", tabs: ["La visión del negocio", "Conversaciones", "Trabajo organizado"], descriptions: ["Ve lo que necesita atención en toda la empresa, en un solo lugar.", "Conecta las conversaciones con clientes con las personas y el trabajo detrás de ellas.", "Convierte la forma de trabajar del equipo en tableros, calendarios y procesos reutilizables."], caption: "Vista previa del producto en desarrollo. La interfaz y las capacidades siguen evolucionando.", alt: ["Base de conocimiento de CompanyONE en una computadora portátil", "Bandeja de entrada compartida de CompanyONE con conversaciones de clientes", "Calendario de CompanyONE con eventos de varios días"], importTitle: "Trae el trabajo que ya hiciste.", importBody: "Empieza con los registros que ya tienes. Importa datos de hojas de cálculo y otros sistemas, y organízalos según la forma de trabajar de tu empresa.", sources: ["Hojas de cálculo", "Registros de clientes", "Otros sistemas"], destination: "El contexto de tu empresa", importNote: "Un punto de partida útil. Nunca una página en blanco." },
  team: { kicker: "Conoce a tus nuevos compañeros", title: "Van más allá de las respuestas. Ayudan al negocio a avanzar.", body: "Agent One y Dev One son agentes privados integrados en CompanyONE. Trabajan con el contexto de tu empresa y junto a tu gente.", agentRole: "Trabaja en tu negocio.", agentBody: "Pide un resultado. Agent One usa el sistema de información y las herramientas conectadas para organizar registros, ejecutar tareas y devolver los resultados al trabajo de tu empresa.", devRole: "Trabaja en tu sistema.", devBody: "Describe lo que necesita cambiar. Dev One ayuda a personalizar flujos, ampliar módulos y crear capacidades a medida que tu empresa evoluciona.", agentTasks: ["Entiende el contexto", "Coordina el trabajo", "Mantiene la información conectada"], devTasks: ["Personaliza flujos", "Crea nuevas capacidades", "Ayuda a mantener el sistema"], note: "Tu gente marca la dirección. Los agentes trabajan a su lado." },
  story: { title: "De una hoja de cálculo a una mejor forma de trabajar.", body: "Una empresa del beta participa en eventos durante todo el año. Su hoja de cálculo guardaba el calendario, pero las reservas de viaje y las asignaciones de equipo necesitaban un proceso compartido. La empresa llevó ese trabajo a CompanyONE y adaptó el sistema a su operación.", request: "“Ayúdanos a organizar nuestros eventos, reservas de viaje y equipos.”", steps: [["Trae el trabajo existente", "Agent One recomendó un tablero Kanban e importó los eventos existentes, para que el equipo empezara con sus propios registros."], ["Adáptalo al equipo", "Una tarjeta reutilizable reunió reservas de hotel, vuelos y autos de alquiler en una lista. Las etiquetas incorporaron las asignaciones de equipo al mismo proceso."], ["Amplía las posibilidades", "El agente sugirió un campo de fecha final para eventos de varios días. La necesidad se convirtió en una mejora del sistema, conectando las fechas del evento con su vista en el calendario."]], caption: "Planificación de eventos en CompanyONE. Datos de ejemplo." },
  modules: { title: "Una base sólida. Un futuro abierto.", body: "Empieza con módulos prácticos de ERP y CRM. Agrega, adapta y amplía mientras tu negocio encuentra su propia forma de trabajar.", items: [["Relaciones", "Clientes, empresas y sus historiales."], ["Bandeja de entrada", "Conversaciones con clientes en un solo lugar."], ["Pipeline", "Oportunidades y próximos pasos."], ["Tableros", "Proyectos, calendarios y trabajo reutilizable."], ["Conocimiento", "El contexto que hace única a tu empresa."], ["Espacios", "Equipos, marcas y contextos de negocio separados."]], final: "Estos son puntos de partida. Tu empresa define lo que sigue." },
  faq: {
    kicker: "Preguntas frecuentes", title: "Qué es CompanyONE — y qué no es.", intro: "Respuestas directas para dueños de pequeños negocios. Abre cualquier pregunta para ver detalles que tu equipo, asesor o un agente de software puede usar para evaluar CompanyONE.", expandAll: "Abrir todas", collapseAll: "Cerrar todas", label: "Preguntas frecuentes sobre CompanyONE",
    items: [
      ["¿Qué es CompanyONE?", "CompanyONE es un sistema operativo privado y autoalojado para dirigir una pequeña empresa.", "Reúne clientes, ventas, conversaciones, trabajo y conocimiento de la empresa en un sistema de información conectado. Agent One trabaja con ese contexto compartido para organizar la información y realizar el trabajo. Cuando la empresa necesita cambiar el propio sistema, Dev One puede crear y probar nuevos módulos, flujos y capacidades para revisión humana."],
      ["¿Para quién es?", "Es software empresarial que posees, personalizas, amplías y pones a trabajar para tu empresa.", "Es especialmente útil cuando la información importante está dispersa entre herramientas, cuando la forma de trabajar de la empresa no cabe en una plantilla genérica o cuando los dueños quieren mayor control sobre su sistema y sus datos. Si la empresa solo necesita una función sencilla y estandarizada, un SaaS convencional todavía puede ser la opción más fácil."],
      ["¿Qué funciones incluye?", "Obtienes un panel del negocio, bandeja compartida de clientes, CRM y pipeline de ventas, gestión de anuncios, tableros y calendarios de proyectos, una base de conocimiento de la empresa, espacios para varias empresas y Agent One.", "El panel muestra la visión operativa de la empresa. La bandeja compartida reúne el chat del sitio web, mensajes de texto y correo electrónico. El CRM y el pipeline de ventas organizan contactos, actividades, oportunidades y próximos pasos. La gestión de anuncios conecta el rendimiento de Google y Meta con acciones controladas. La gestión de proyectos ofrece tableros, calendarios, plantillas, listas de verificación y archivos. La base de conocimiento es la fuente confiable de la empresa, los espacios mantienen separadas las distintas empresas y Agent One trabaja con todo este contexto. Estas funciones son puntos de partida, no el límite fijo del sistema. Dev One puede agregar módulos, flujos y capacidades a medida que evolucionan las necesidades de la empresa."],
      ["¿Es solo otro chatbot?", "No. Agent One trabaja dentro del mismo sistema de información donde viven el trabajo y el conocimiento de la empresa.", "Un chatbot genérico suele responder a partir de una conversación y de lo que alguien pega en ella. Agent One puede usar el espacio activo de la empresa, consultar su fuente confiable, trabajar con registros autorizados, preparar cambios exactos para su aprobación y enlazar a las personas con el trabajo resultante. Es parte del sistema operativo, no una ventana de chat separada y sin conexión con el negocio."],
      ["¿Qué no es?", "No es un SaaS igual para todos, un constructor no-code vacío ni un sistema que realiza acciones importantes sin ti.", "El sistema comienza con capacidades útiles para el negocio y después se adapta a la empresa. Tampoco funciona necesariamente sin conexión: el correo electrónico, los mensajes de texto, los anuncios, el acceso a internet y los proveedores de los agentes todavía dependen de sus respectivos servicios. El sistema coordina esas herramientas mientras mantiene el sistema de información central bajo el control de la empresa."],
      ["¿Por qué elegirlo en lugar de un SaaS común?", "Elígelo cuando adaptar el sistema al negocio importa más que adaptar el negocio al software.", "Un SaaS común es conveniente para necesidades estandarizadas, pero varios productos pueden dejar a la empresa con suscripciones separadas, datos duplicados y flujos definidos por distintos proveedores. Este sistema ofrece una base conectada que la empresa controla y puede ampliar. La idea no es que todo SaaS sea malo; es para negocios que necesitan más continuidad, contexto y capacidad de adaptación que la que puede ofrecer una colección de herramientas fijas."],
      ["¿Puede reemplazar nuestro software actual?", "Sí. Si todavía no puede reemplazar una herramienta hoy, puede evolucionar para reemplazarla — a la velocidad y en la dirección que elija tu empresa.", "Empieza por los flujos que más importan. El sistema puede absorber más funciones con el tiempo, en el orden que la empresa priorice. Agent One ayuda a operar el negocio en el sistema actual, mientras Dev One crea las siguientes capacidades. Las prioridades de la empresa, no la hoja de ruta fija de un proveedor, determinan la secuencia. Redes externas como la entrega de correo, los mensajes de texto y las plataformas de anuncios pueden seguir siendo infraestructura conectada aun cuando sus flujos de negocio se administren dentro de tu sistema."],
      ["¿Qué pasa cuando cambia nuestro negocio?", "El sistema puede cambiar con él.", "Una necesidad nueva puede resolverse ajustando un flujo, creando una plantilla, agregando un módulo o ampliando el sistema. Para cambios más profundos, Dev One puede convertir el resultado deseado en un cambio probado del sistema. Una persona revisa el trabajo antes de que llegue al sistema activo de la empresa. La empresa no tiene que esperar a que la hoja de ruta de un proveedor genérico reconozca cada necesidad específica."],
      ["¿Dónde viven nuestros datos?", "Tu empresa controla la computadora, la base de datos, los archivos y los respaldos que usa su instalación.", "Tu instalación es autoalojada, en lugar de colocar a todos los clientes dentro de una sola aplicación compartida del proveedor. Cada instalación nueva usa una base de datos nueva y credenciales creadas para esa empresa; los paquetes de versión no contienen datos, archivos, secretos ni respaldos de otra empresa. Los proveedores conectados todavía procesan la información necesaria para prestar sus servicios, por lo que autoalojado no significa que ningún servicio externo reciba datos."],
      ["¿Agent One puede actuar sin nuestra aprobación?", "Los cambios importantes permanecen bajo control humano.", "Agent One puede leer información autorizada, explicar lo que encontró y preparar el trabajo. Los cambios en los registros de la empresa y las acciones externas con consecuencias requieren una aprobación explícita y específica, vinculada al administrador, el espacio, el objetivo y los valores solicitados. Los permisos de usuario y los límites entre espacios también restringen lo que cada persona o agente puede consultar."],
      ["¿Necesitamos un equipo técnico?", "No. Agent One y Dev One son tu equipo de operaciones e ingeniería.", "Agent One trabaja junto al dueño para comprender el contexto de la empresa, organizar el trabajo y realizar acciones operativas aprobadas. Dev One crea, prueba, mantiene y amplía el sistema a medida que cambia el negocio. El dueño marca la dirección y aprueba los cambios importantes, mientras los agentes se encargan del trabajo operativo y técnico."],
      ["¿Una instalación puede admitir más de una empresa?", "Sí. Una instalación puede administrar varias empresas como espacios separados.", "Cada espacio mantiene separados sus registros, archivos, identidad visual, búsquedas, conocimiento y contexto operativo. Las cuentas y la administración de toda la instalación se gestionan de forma centralizada. Cuando Agent One trabaja con información de la empresa, el espacio activo determina qué registros y contexto se aplican."],
      ["¿Qué significa “tu sistema”?", "Tu empresa recibe módulos y funciones estándar, y puede desarrollar otros personalizados que te pertenecen solo a ti.", "Tu sistema comienza con una base estándar de módulos y funciones disponible para todos los clientes. Cuando la empresa necesita algo específico, Dev One puede crear un módulo, flujo o capacidad personalizada para la instalación de esa empresa. Esas capacidades personalizadas pertenecen únicamente a esa empresa, y la empresa decide cómo evoluciona su sistema."],
      ["¿Está listo para usar?", "Sí. Todavía está en sus primeras etapas, pero ya ofrece muchas capacidades útiles — y se agregan más con regularidad.", "El sistema está listo para flujos reales de empresas hoy y continúa expandiéndose. Las versiones regulares agregan funciones estándar y mejoras. Las prioridades de cada empresa pueden orientar los próximos módulos, flujos y capacidades personalizados que construya Dev One."]
    ]
  },
  closing: { title: ["Tu empresa.", "Un solo sistema.", "CompanyONE"], body: "Un sistema que se vuelve más tuyo con cada mejora.", note: "En desarrollo activo. Creado con pequeños negocios reales.", top: "Volver al inicio" },
};
export const COPY: Record<Locale, Copy> = { en, "pt-BR": ptBR, "es-419": es419 };
export function normalizeLocale(value: string | null | undefined): Locale | null {
  const normalized = value?.toLowerCase();
  if (normalized?.startsWith("pt")) return "pt-BR";
  if (normalized?.startsWith("es")) return "es-419";
  if (normalized?.startsWith("en")) return "en";
  return null;
}
